// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3O2SjX1PSMf8A5cW50lzxdl0zoiCChdA',
    appId: '1:506035064711:web:2fe942cde90737e11ecd22',
    messagingSenderId: '506035064711',
    projectId: 'progress-me-5a560',
    authDomain: 'progress-me-5a560.firebaseapp.com',
    storageBucket: 'progress-me-5a560.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYV8HMtlDk_LuL2pNa4K_NLiSz_YFK_E8',
    appId: '1:506035064711:android:c99a13261bb02e281ecd22',
    messagingSenderId: '506035064711',
    projectId: 'progress-me-5a560',
    storageBucket: 'progress-me-5a560.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS1Oa47CGsgpG7FMuDz0Yx1_2jzknVsu4',
    appId: '1:506035064711:ios:7738ed68bd66b9fc1ecd22',
    messagingSenderId: '506035064711',
    projectId: 'progress-me-5a560',
    storageBucket: 'progress-me-5a560.appspot.com',
    iosClientId: '506035064711-dpoo5qcqsklae5kg33l3sllclpf6kcvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.profileMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS1Oa47CGsgpG7FMuDz0Yx1_2jzknVsu4',
    appId: '1:506035064711:ios:7738ed68bd66b9fc1ecd22',
    messagingSenderId: '506035064711',
    projectId: 'progress-me-5a560',
    storageBucket: 'progress-me-5a560.appspot.com',
    iosClientId: '506035064711-dpoo5qcqsklae5kg33l3sllclpf6kcvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.profileMe',
  );
}
